# Form implementation generated from reading ui file 'presentation/ui/buy_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BuyDialog(object):
    def setupUi(self, BuyDialog):
        BuyDialog.setObjectName("BuyDialog")
        BuyDialog.resize(380, 220)
        self.layoutWidget = QtWidgets.QWidget(parent=BuyDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 340, 160))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblFrom = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblFrom.setObjectName("lblFrom")
        self.gridLayout.addWidget(self.lblFrom, 0, 0, 1, 1)
        self.txtFrom = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtFrom.setObjectName("txtFrom")
        self.gridLayout.addWidget(self.txtFrom, 0, 1, 1, 1)
        self.lblTo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTo.setObjectName("lblTo")
        self.gridLayout.addWidget(self.lblTo, 1, 0, 1, 1)
        self.txtTo = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtTo.setObjectName("txtTo")
        self.gridLayout.addWidget(self.txtTo, 1, 1, 1, 1)
        self.lblAmount = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblAmount.setObjectName("lblAmount")
        self.gridLayout.addWidget(self.lblAmount, 2, 0, 1, 1)
        self.txtAmount = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtAmount.setObjectName("txtAmount")
        self.gridLayout.addWidget(self.txtAmount, 2, 1, 1, 1)
        self.btnBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.btnBox.setObjectName("btnBox")
        self.gridLayout.addWidget(self.btnBox, 3, 0, 1, 2)

        self.retranslateUi(BuyDialog)
        QtCore.QMetaObject.connectSlotsByName(BuyDialog)

    def retranslateUi(self, BuyDialog):
        _translate = QtCore.QCoreApplication.translate
        BuyDialog.setWindowTitle(_translate("BuyDialog", "Comprar Moneda"))
        self.lblFrom.setText(_translate("BuyDialog", "Moneda origen"))
        self.txtFrom.setPlaceholderText(_translate("BuyDialog", "ARS"))
        self.lblTo.setText(_translate("BuyDialog", "Moneda destino"))
        self.txtTo.setPlaceholderText(_translate("BuyDialog", "USD"))
        self.lblAmount.setText(_translate("BuyDialog", "Cantidad destino"))
        self.txtAmount.setPlaceholderText(_translate("BuyDialog", "ej: 100.00"))
