# Form implementation generated from reading ui file 'presentation/ui/dialog_accounts.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 200)
        self.accountList = QtWidgets.QComboBox(parent=Dialog)
        self.accountList.setGeometry(QtCore.QRect(30, 30, 300, 32))
        self.accountList.setObjectName("accountList")
        self.accountList.addItem("")
        self.accountList.addItem("")
        self.accountList.addItem("")
        self.accountList.addItem("")
        self.accountList.addItem("")
        self.btnOKCancel = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.btnOKCancel.setGeometry(QtCore.QRect(30, 120, 300, 32))
        self.btnOKCancel.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.btnOKCancel.setObjectName("btnOKCancel")

        self.retranslateUi(Dialog)
        self.btnOKCancel.accepted.connect(Dialog.accept) # type: ignore
        self.btnOKCancel.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nueva Cuenta"))
        self.accountList.setItemText(0, _translate("Dialog", "USD"))
        self.accountList.setItemText(1, _translate("Dialog", "EUR"))
        self.accountList.setItemText(2, _translate("Dialog", "ARS"))
        self.accountList.setItemText(3, _translate("Dialog", "BRL"))
        self.accountList.setItemText(4, _translate("Dialog", "BTC"))
