# Form implementation generated from reading ui file 'presentation/ui/init_menu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InitMenu(object):
    def setupUi(self, InitMenu):
        InitMenu.setObjectName("InitMenu")
        InitMenu.resize(400, 300)
        InitMenu.setStyleSheet("QDialog{background:#1e1e1e;}")
        self.layoutWidget = QtWidgets.QWidget(parent=InitMenu)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 50, 280, 180))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnLogin = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnLogin.setStyleSheet("QPushButton{background:#0e639c;border:none;border-radius:6px;padding:10px;color:#fff;font-size:14px;font-weight:bold;} QPushButton:hover{background:#1177bb;} QPushButton:pressed{background:#094771;}")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)
        self.btnRegister = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnRegister.setStyleSheet("QPushButton{background:#0e639c;border:none;border-radius:6px;padding:10px;color:#fff;font-size:14px;font-weight:bold;} QPushButton:hover{background:#1177bb;} QPushButton:pressed{background:#094771;}")
        self.btnRegister.setObjectName("btnRegister")
        self.verticalLayout.addWidget(self.btnRegister)
        self.btnExit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnExit.setStyleSheet("QPushButton{background:#c62828;border:none;border-radius:6px;padding:10px;color:#fff;font-size:14px;font-weight:bold;} QPushButton:hover{background:#e53935;} QPushButton:pressed{background:#8e0000;}")
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout.addWidget(self.btnExit)

        self.retranslateUi(InitMenu)
        QtCore.QMetaObject.connectSlotsByName(InitMenu)

    def retranslateUi(self, InitMenu):
        _translate = QtCore.QCoreApplication.translate
        InitMenu.setWindowTitle(_translate("InitMenu", "Bienvenido"))
        self.btnLogin.setText(_translate("InitMenu", "Login"))
        self.btnRegister.setText(_translate("InitMenu", "Registro"))
        self.btnExit.setText(_translate("InitMenu", "Salir"))
