# Form implementation generated from reading ui file 'presentation/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(420, 300)
        LoginDialog.setStyleSheet("QDialog{background:#1e1e1e;}")
        self.layoutWidget = QtWidgets.QWidget(parent=LoginDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 340, 220))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setStyleSheet("QLabel{font-size:22px; font-weight:600; color:#d4d4d4;}")
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 2)
        self.lblUser = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblUser.setStyleSheet("QLabel{color:#d4d4d4;}")
        self.lblUser.setObjectName("lblUser")
        self.gridLayout.addWidget(self.lblUser, 1, 0, 1, 1)
        self.txtUser = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtUser.setStyleSheet("QLineEdit{background:#252526; border:1px solid #3c3c3c; border-radius:6px; padding:8px; color:#d4d4d4;}\n"
"QLineEdit:focus{border:1px solid #007acc;}")
        self.txtUser.setObjectName("txtUser")
        self.gridLayout.addWidget(self.txtUser, 1, 1, 1, 1)
        self.lblPass = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblPass.setStyleSheet("QLabel{color:#d4d4d4;}")
        self.lblPass.setObjectName("lblPass")
        self.gridLayout.addWidget(self.lblPass, 2, 0, 1, 1)
        self.txtPass = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass.setStyleSheet("QLineEdit{background:#252526; border:1px solid #3c3c3c; border-radius:6px; padding:8px; color:#d4d4d4;}\n"
"QLineEdit:focus{border:1px solid #007acc;}")
        self.txtPass.setObjectName("txtPass")
        self.gridLayout.addWidget(self.txtPass, 2, 1, 1, 1)
        self.lblError = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblError.setText("")
        self.lblError.setStyleSheet("QLabel{color:#f28b82;}")
        self.lblError.setObjectName("lblError")
        self.gridLayout.addWidget(self.lblError, 3, 0, 1, 2)
        self.btnBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.btnBox.setObjectName("btnBox")
        self.gridLayout.addWidget(self.btnBox, 4, 0, 1, 2)

        self.retranslateUi(LoginDialog)
        self.btnBox.accepted.connect(LoginDialog.accept) # type: ignore
        self.btnBox.rejected.connect(LoginDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Iniciar sesión"))
        self.lblTitle.setText(_translate("LoginDialog", "Login"))
        self.lblUser.setText(_translate("LoginDialog", "Usuario"))
        self.txtUser.setPlaceholderText(_translate("LoginDialog", "tu_usuario"))
        self.lblPass.setText(_translate("LoginDialog", "Contraseña"))
        self.txtPass.setPlaceholderText(_translate("LoginDialog", "••••••••"))
