# Form implementation generated from reading ui file 'presentation/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 251, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.leftMenu = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.leftMenu.setContentsMargins(0, 0, 0, 0)
        self.leftMenu.setObjectName("leftMenu")
        self.btnAddAccount = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnAddAccount.setObjectName("btnAddAccount")
        self.leftMenu.addWidget(self.btnAddAccount)
        self.btnDeposit = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnDeposit.setObjectName("btnDeposit")
        self.leftMenu.addWidget(self.btnDeposit)
        self.btnBuy = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnBuy.setObjectName("btnBuy")
        self.leftMenu.addWidget(self.btnBuy)
        self.btnSell = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnSell.setObjectName("btnSell")
        self.leftMenu.addWidget(self.btnSell)
        self.btnLogout = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btnLogout.setObjectName("btnLogout")
        self.leftMenu.addWidget(self.btnLogout)
        self.AccountTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.AccountTable.setGeometry(QtCore.QRect(300, 10, 480, 520))
        self.AccountTable.setObjectName("AccountTable")
        self.AccountTable.setColumnCount(2)
        self.AccountTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.AccountTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.AccountTable.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wallet FX"))
        self.btnAddAccount.setText(_translate("MainWindow", "Crear Cuenta"))
        self.btnDeposit.setText(_translate("MainWindow", "Depositar ARS"))
        self.btnBuy.setText(_translate("MainWindow", "Comprar Moneda"))
        self.btnSell.setText(_translate("MainWindow", "Vender Moneda"))
        self.btnLogout.setText(_translate("MainWindow", "Cerrar Sesión"))
        item = self.AccountTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Moneda"))
        item = self.AccountTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Monto"))
