# Form implementation generated from reading ui file 'presentation/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(420, 340)
        RegisterDialog.setStyleSheet("QDialog{background:#1e1e1e;}")
        self.layoutWidget = QtWidgets.QWidget(parent=RegisterDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 340, 260))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setStyleSheet("QLabel{font-size:20px;font-weight:600;color:#d4d4d4;}")
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout.addWidget(self.lblTitle, 0, 0, 1, 2)
        self.lblUser = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblUser.setStyleSheet("QLabel{color:#d4d4d4;}")
        self.lblUser.setObjectName("lblUser")
        self.gridLayout.addWidget(self.lblUser, 1, 0, 1, 1)
        self.txtUser = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtUser.setStyleSheet("QLineEdit{background:#252526;border:1px solid #3c3c3c;border-radius:6px;padding:8px;color:#d4d4d4;} QLineEdit:focus{border:1px solid #007acc;}")
        self.txtUser.setObjectName("txtUser")
        self.gridLayout.addWidget(self.txtUser, 1, 1, 1, 1)
        self.lblPass = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblPass.setStyleSheet("QLabel{color:#d4d4d4;}")
        self.lblPass.setObjectName("lblPass")
        self.gridLayout.addWidget(self.lblPass, 2, 0, 1, 1)
        self.txtPass = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass.setStyleSheet("QLineEdit{background:#252526;border:1px solid #3c3c3c;border-radius:6px;padding:8px;color:#d4d4d4;} QLineEdit:focus{border:1px solid #007acc;}")
        self.txtPass.setObjectName("txtPass")
        self.gridLayout.addWidget(self.txtPass, 2, 1, 1, 1)
        self.lblPass2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblPass2.setStyleSheet("QLabel{color:#d4d4d4;}")
        self.lblPass2.setObjectName("lblPass2")
        self.gridLayout.addWidget(self.lblPass2, 3, 0, 1, 1)
        self.txtPass2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtPass2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPass2.setStyleSheet("QLineEdit{background:#252526;border:1px solid #3c3c3c;border-radius:6px;padding:8px;color:#d4d4d4;} QLineEdit:focus{border:1px solid #007acc;}")
        self.txtPass2.setObjectName("txtPass2")
        self.gridLayout.addWidget(self.txtPass2, 3, 1, 1, 1)
        self.lblError = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblError.setText("")
        self.lblError.setStyleSheet("QLabel{color:#f28b82;}")
        self.lblError.setObjectName("lblError")
        self.gridLayout.addWidget(self.lblError, 4, 0, 1, 2)
        self.btnBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok|QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.btnBox.setObjectName("btnBox")
        self.gridLayout.addWidget(self.btnBox, 5, 0, 1, 2)

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Registro"))
        self.lblTitle.setText(_translate("RegisterDialog", "Crear cuenta"))
        self.lblUser.setText(_translate("RegisterDialog", "Usuario"))
        self.txtUser.setPlaceholderText(_translate("RegisterDialog", "nuevo_usuario"))
        self.lblPass.setText(_translate("RegisterDialog", "Contraseña"))
        self.txtPass.setPlaceholderText(_translate("RegisterDialog", "••••••••"))
        self.lblPass2.setText(_translate("RegisterDialog", "Repetir contraseña"))
        self.txtPass2.setPlaceholderText(_translate("RegisterDialog", "••••••••"))
